- name: Get secrects from vault
  hosts: local
  connection: local
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/test:demo token={{ vault_token }} url=http://http://vault.kommanuthala.store:8200') }}"