- name: Get secrets from vault
  hosts: localhost
  connection: local
  tasks:
    - name: print 
      ansible.builtin.debug:
        msg: "{{ lookup('hashi_vault', 'secret=test/data/demo:username token={{ vault_token }} url=http://vault.kommanuthala.store:8200')}}"