- name: Get secrects from vault
  hosts: localhost
  connection: local
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=test/demo:username token={{ vault_token }} url=http://vault-internal.kommanuthala.store:8200') }}"