- name: Frontend setup
  hosts: all
  tasks:
    - name: Disabled default nginx
      ansible.builtin.shell: dnf module disable nginx
    
    - name: Install nginx 24
      ansible.builtin.shell: dnf module enable nginx:1.24 -y 
  
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
